# Задание для индивидуальной работы No3 (Вариант А)

### 1.Блок. Pandas

In [66]:
import pandas as pd

In [85]:
df = pd.read_csv("competition_1.csv", delimiter=";")
df.head()

,Фамилия,Имя,Пол,Год рождения,"Бег 1000 метров, мин. и сек.","Бег 30 метров, сек.","Прыжок в длину с места, см"
0,Абдуллаев,Денис,м,1998,"3,42","4,72",188
1,Абдуллаев,Темур,м,1999,"5,12","5,63",187
2,Абраменцев,Владислав,м,1997,"5,52","5,42",223
3,Абсалямов,Илья,м,1999,"5,43","4,92",237
4,Авдонин,Александр,м,1998,"4,38","4,71",219

In [86]:
def time_to_seconds(val):
    if pd.isna(val):
        return None
    val_str = str(val).replace(",", ".")
    parts = val_str.split(".")
    if len(parts) == 2:
        return int(parts[0]) * 60 + int(parts[1])
    return int(val_str) * 60


df["1000 м, сек"] = df["Бег 1000 метров, мин. и сек."].apply(time_to_seconds)

In [87]:
df["Бег 30 метров, сек."] = (
    df["Бег 30 метров, сек."].str.replace(",", ".").astype(float)
)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Фамилия                       1000 non-null   str
 1   Имя                           1000 non-null   str
 2   Пол                           1000 non-null   str
 3   Год рождения                  1000 non-null   int64
 4   Бег 1000 метров, мин. и сек.  1000 non-null   str
 5   Бег 30 метров, сек.           1000 non-null   float64
 6   Прыжок в длину с места, см    1000 non-null   int64
 7   1000 м, сек                   1000 non-null   int64
dtypes: float64(1), int64(3), str(4)
memory usage: 62.6 KB

#### 1.1

In [88]:
df.groupby(["Год рождения", "Пол"])["1000 м, сек"].agg(
    Среднее="mean", Медиана="median"
).round(2)

                  Среднее  Медиана
Год рождения Пол
1996         ж     283.81    285.0
             м     284.06    286.0
1997         ж     280.82    278.0
             м     286.89    287.5
1998         ж     290.32    292.0
             м     287.74    283.0
1999         ж     287.82    292.0
             м     285.00    285.0

#### 1.2

In [89]:
sports = {
    "Бег 1000 метров, мин. и сек.": True,
    "Бег 30 метров, сек.": True,
    "Прыжок в длину с места, см ": False,
}


for sport, ascending in sports.items():
    print(f"\n{'=' * 60}")
    print(f"ВИД: {sport}")
    print(f"{'=' * 60}")

    df["Место"] = df.groupby(["Год рождения", "Пол"])[sport].rank(
        method="dense", ascending=ascending
    )

    winners = df[df["Место"] <= 3].copy()

    for year in sorted(winners["Год рождения"].unique()):
        for gender in ["ж", "м"]:
            subset = winners[
                (winners["Год рождения"] == year) & (winners["Пол"] == gender)
            ].sort_values("Место")

            if not subset.empty:
                print(
                    f"\n--- {year} год, {'девочки' if gender == 'д' else 'мальчики'} ---"
                )
                print(subset[["Место", "Фамилия", "Имя", sport]].to_string(index=False))

============================================================
ВИД: Бег 1000 метров, мин. и сек.
============================================================

--- 1996 год, мальчики ---
 Место      Фамилия       Имя Бег 1000 метров, мин. и сек.
   1.0      Коркина Анастасия                         3,28
   2.0      Иванова      Анна                          3,3
   3.0 Трапезникова     Мария                         3,33

--- 1996 год, мальчики ---
 Место  Фамилия    Имя Бег 1000 метров, мин. и сек.
   1.0   Бурсов Никита                         3,28
   2.0 Бессонов Кирилл                          3,3
   3.0  Бохонов  Антон                         3,33

--- 1997 год, мальчики ---
 Место   Фамилия       Имя Бег 1000 метров, мин. и сек.
   1.0  Бирюкова     Злата                         3,28
   1.0 Гайдамака Екатерина                         3,28
   1.0   Мошкина   Татьяна                         3,28
   2.0  Яруллина   Татьяна                          3,3
   3.0  Соколова     Марта                         3,32

--- 1997 год, мальчики ---
 Место Фамилия     Имя Бег 1000 метров, мин. и сек.
   1.0 Чеканов Евгений                         3,28
   2.0 Дроздов    Петр                          3,3
   3.0   Дюкин  Никита                         3,32
   3.0 Меликов  Кирилл                         3,32

--- 1998 год, мальчики ---
 Место    Фамилия       Имя Бег 1000 метров, мин. и сек.
   1.0  Крутякова     Мария                         3,32
   2.0  Альмяшева Елизавета                         3,33
   3.0 Золотарёва    Ксения                         3,35

--- 1998 год, мальчики ---
 Место  Фамилия     Имя Бег 1000 метров, мин. и сек.
   1.0 Зеленцов  Андрей                         3,28
   2.0     Еров Алексей                          3,3
   3.0   Руйбис  Никита                         3,37

--- 1999 год, мальчики ---
 Место     Фамилия     Имя Бег 1000 метров, мин. и сек.
   1.0    Ермолова    Анна                         3,28
   2.0      Орлова  Ксения                         3,32
   2.0    Троилина    Юлия                         3,32
   3.0   Бузовкина Людмила                         3,33
   3.0  Новосёлова   Алина                         3,33
   3.0 Кадыркулова   Ольга                         3,33

--- 1999 год, мальчики ---
 Место  Фамилия     Имя Бег 1000 метров, мин. и сек.
   1.0 Стручков   Фёдор                         3,28
   2.0 Родюшкин   Игорь                          3,3
   2.0 Толкачев Алексей                          3,3
   3.0     Тиль Евгений                         3,32

============================================================
ВИД: Бег 30 метров, сек.
============================================================

--- 1996 год, мальчики ---
 Место   Фамилия     Имя  Бег 30 метров, сек.
   1.0 Скоберева   Мария                 4.02
   1.0 Чегодаева   Алина                 4.02
   2.0  Никитина   Ольга                 4.12
   2.0 Короткова   Софья                 4.12
   3.0  Воронина Татьяна                 4.22

--- 1996 год, мальчики ---
 Место  Фамилия       Имя  Бег 30 метров, сек.
   1.0 Курбатов Александр                 4.02
   2.0 Платонов  Гахраман                 4.03
   3.0  Малютин    Микаэл                 4.06
   3.0  Мастяев      Арзу                 4.06
   3.0      Цой    Никита                 4.06

--- 1997 год, мальчики ---
 Место    Фамилия       Имя  Бег 30 метров, сек.
   1.0    Алимова Екатерина                 4.00
   2.0   Морозова      Юлия                 4.01
   3.0 Дементьева     Ольга                 4.05

--- 1997 год, мальчики ---
 Место  Фамилия   Имя  Бег 30 метров, сек.
   1.0  Демидов Антон                 4.01
   2.0 Горбатюк Антон                 4.02
   3.0   Бывших Рубен                 4.03

--- 1998 год, мальчики ---
 Место   Фамилия       Имя  Бег 30 метров, сек.
   1.0 Керенцева   Наталия                 4.02
   2.0    Мухина Анастасия                 4.06
   3.0  Семёнова     Елена                 4.14

--- 1998 год, мальчики ---
 Место   Фамилия       Имя  Бег 30 метров, сек.
   1.0  Стукалов     Борис                 4.02
   2.0    Климов Александр                 4.05
   3.0 Мазуренко    Максим                 4.10
   3.0     Робак   Алексей                 4.10

--- 1999 год, мальчики ---
 Место   Фамилия   Имя  Бег 30 метров, сек.
   1.0  Куликова Дарья                 4.12
   2.0 Филиппова  Анна                 4.13
   3.0 Игнатьева Мария                 4.21

--- 1999 год, мальчики ---
 Место  Фамилия     Имя  Бег 30 метров, сек.
   1.0  Уваркин Тимофей                 4.01
   2.0   Шапель Миралем                 4.09
   3.0 Нестеров Виталий                 4.10

============================================================
ВИД: Прыжок в длину с места, см
============================================================

--- 1996 год, мальчики ---
 Место     Фамилия    Имя  Прыжок в длину с места, см
   1.0     Логвина  Ирина                          236
   2.0 Загидуллина  Лейли                          235
   2.0   Стукалина Оксана                          235
   3.0   Журавлева   Алла                          234

--- 1996 год, мальчики ---
 Место   Фамилия       Имя  Прыжок в длину с места, см
   1.0  Молчанов    Виктор                          237
   2.0 Станкевич Александр                          236
   3.0  Нерсисян  Владимир                          235
   3.0 Кильдишов    Никита                          235
   3.0  Парфенов   Дмитрий                          235

--- 1997 год, мальчики ---
 Место      Фамилия     Имя  Прыжок в длину с места, см
   1.0      Боброва Наталья                          234
   1.0 Приказчикова   Дарья                          234
   2.0    Степанова   Мария                          233
   3.0        Деева  Ксения                          232

--- 1997 год, мальчики ---
 Место    Фамилия       Имя  Прыжок в длину с места, см
   1.0      Ершов Владислав                          237
   1.0      Лунев      Петр                          237
   2.0    Кузьмин   Ярослав                          235
   3.0 Зборовский   Алексей                          234

--- 1998 год, мальчики ---
 Место   Фамилия       Имя  Прыжок в длину с места, см
   1.0 Тишабаева   Надежда                          235
   1.0  Смирнова     Олеся                          235
   2.0   Петрова Анастасия                          234
   3.0  Нефедова   Татьяна                          231

--- 1998 год, мальчики ---
 Место     Фамилия     Имя  Прыжок в длину с места, см
   1.0       Ларин  Михаил                          235
   1.0     Терехов   Артём                          235
   1.0 Федоровский  Максим                          235
   2.0   Никульшин Георгий                          234
   3.0        Еров Алексей                          232
   3.0     Керимов Дмитрий                          232

--- 1999 год, мальчики ---
 Место  Фамилия    Имя  Прыжок в длину с места, см
   1.0  Бойцова  Ольга                          236
   2.0 Сафонова Полина                          235
   3.0 Арбузова  Мария                          234

--- 1999 год, мальчики ---
 Место   Фамилия     Имя  Прыжок в длину с места, см
   1.0 Абсалямов    Илья                          237
   1.0     Попов   Павел                          237
   2.0    Шумари Алексей                          235
   3.0   Ермаков Николай                          234

#### 1.3

In [98]:
sports = {
    "1000 м, сек": True,  # Используем переведенное в секунды время
    "Бег 30 метров, сек.": True,
    "Прыжок в длину с места, см ": False,
}

girls = df[df["Пол"] == "ж"].copy()

for sport, ascending in sports.items():
    print(f"\n{'=' * 60}")
    print(f"ВИД СПОРТА: {sport}")
    print(f"{'=' * 60}")

    # Считаем ранг внутри каждого года для этого вида спорта
    girls[f"Ранг {sport}"] = girls.groupby(["Год рождения"])[sport].rank(
        method="min", ascending=ascending
    )

    # Отбираем ТОП-5
    top5 = girls[girls[f"Ранг {sport}"] <= 5].copy()

    # Выводим результаты по годам
    for year in sorted(top5["Год рождения"].unique()):
        group = top5[top5["Год рождения"] == year].sort_values(f"Ранг {sport}")

        print(f"\n--- {year} год ---")
        print(group[[f"Ранг {sport}", "Фамилия", "Имя", sport]].to_string(index=False))

============================================================
ВИД СПОРТА: 1000 м, сек
============================================================

--- 1996 год ---
 Ранг 1000 м, сек    Фамилия       Имя  1000 м, сек
              1.0    Иванова      Анна          183
              2.0  Андрякова     Ирина          184
              2.0 Артамонова   Татьяна          184
              2.0 Жданникова       Яна          184
              5.0    Коркина Анастасия          208

--- 1997 год ---
 Ранг 1000 м, сек    Фамилия       Имя  1000 м, сек
              1.0   Яруллина   Татьяна          183
              2.0 Костромина   Евгения          184
              2.0 Мухамедова   Камилла          184
              4.0   Богачева   Клавдия          185
              5.0  Гайдамака Екатерина          208
              5.0   Бирюкова     Злата          208
              5.0    Мошкина   Татьяна          208

--- 1998 год ---
 Ранг 1000 м, сек    Фамилия       Имя  1000 м, сек
              1.0   Лазурина Анастасия          184
              1.0   Себелева Екатерина          184
              3.0  Крутякова     Мария          212
              4.0  Альмяшева Елизавета          213
              5.0 Золотарёва    Ксения          215

--- 1999 год ---
 Ранг 1000 м, сек     Фамилия       Имя  1000 м, сек
              1.0      Негара Анастасия          184
              2.0    Ермолова      Анна          208
              3.0    Троилина      Юлия          212
              3.0      Орлова    Ксения          212
              5.0 Кадыркулова     Ольга          213
              5.0   Бузовкина   Людмила          213
              5.0  Новосёлова     Алина          213

============================================================
ВИД СПОРТА: Бег 30 метров, сек.
============================================================

--- 1996 год ---
 Ранг Бег 30 метров, сек.   Фамилия     Имя  Бег 30 метров, сек.
                      1.0 Скоберева   Мария                 4.02
                      1.0 Чегодаева   Алина                 4.02
                      3.0  Никитина   Ольга                 4.12
                      3.0 Короткова   Софья                 4.12
                      5.0  Воронина Татьяна                 4.22

--- 1997 год ---
 Ранг Бег 30 метров, сек.    Фамилия       Имя  Бег 30 метров, сек.
                      1.0    Алимова Екатерина                 4.00
                      2.0   Морозова      Юлия                 4.01
                      3.0 Дементьева     Ольга                 4.05
                      4.0    Ушакова  Виктория                 4.08
                      5.0     Пудова    Ксения                 4.12

--- 1998 год ---
 Ранг Бег 30 метров, сек.   Фамилия       Имя  Бег 30 метров, сек.
                      1.0 Керенцева   Наталия                 4.02
                      2.0    Мухина Анастасия                 4.06
                      3.0  Семёнова     Елена                 4.14
                      4.0   Власова Анастасия                 4.15
                      4.0  Ульянова Екатерина                 4.15

--- 1999 год ---
 Ранг Бег 30 метров, сек.   Фамилия        Имя  Бег 30 метров, сек.
                      1.0  Куликова      Дарья                 4.12
                      2.0 Филиппова       Анна                 4.13
                      3.0 Игнатьева      Мария                 4.21
                      4.0    Шерина  Екатерина                 4.23
                      5.0 Копейцева Александра                 4.26

============================================================
ВИД СПОРТА: Прыжок в длину с места, см
============================================================

--- 1996 год ---
 Ранг Прыжок в длину с места, см      Фамилия    Имя  Прыжок в длину с места, см
                              1.0     Логвина  Ирина                          236
                              2.0 Загидуллина  Лейли                          235
                              2.0   Стукалина Оксана                          235
                              4.0   Журавлева   Алла                          234
                              5.0    Смирнова   Юлия                          231

--- 1997 год ---
 Ранг Прыжок в длину с места, см       Фамилия     Имя  Прыжок в длину с места, см
                              1.0      Боброва Наталья                          234
                              1.0 Приказчикова   Дарья                          234
                              3.0    Степанова   Мария                          233
                              4.0        Деева  Ксения                          232
                              5.0    Бородкина Наталья                          231

--- 1998 год ---
 Ранг Прыжок в длину с места, см    Фамилия       Имя  Прыжок в длину с места, см
                              1.0  Смирнова     Олеся                          235
                              1.0 Тишабаева   Надежда                          235
                              3.0   Петрова Анастасия                          234
                              4.0  Нефедова   Татьяна                          231
                              5.0 Кузнецова      Юлия                          230
                              5.0  Каримова Анастасия                          230
                              5.0 Гапликова     Саяна                          230
                              5.0   Петрова     Дарья                          230

--- 1999 год ---
 Ранг Прыжок в длину с места, см   Фамилия       Имя  Прыжок в длину с места, см
                              1.0  Бойцова     Ольга                          236
                              2.0 Сафонова    Полина                          235
                              3.0 Арбузова     Мария                          234
                              4.0  Ишутина     Дария                          233
                              4.0 Русакова Екатерина                          233